/**
 * Minesweeper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GameMark', 'model/GameStart'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GameMark'), require('../model/GameStart'));
  } else {
    // Browser globals (root is window)
    if (!root.Minesweeper) {
      root.Minesweeper = {};
    }
    root.Minesweeper.Api = factory(root.Minesweeper.ApiClient, root.Minesweeper.GameMark, root.Minesweeper.GameStart);
  }
}(this, function(ApiClient, GameMark, GameStart) {
  'use strict';

  /**
   * Api service.
   * @module api/Api
   * @version 1.0.0
   */

  /**
   * Constructs a new Api.
   * @alias module:api/Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the v1DocsList operation.
     * @callback module:api/Api~v1DocsListCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/Api~v1DocsListCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.v1DocsList = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/docs', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v1GamesCreate operation.
     * @callback module:api/Api~v1GamesCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Starts a new game
     * Starts a new game
     * @param {Object} opts Optional parameters
     * @param {module:model/GameStart} opts.data
     * @param {module:api/Api~v1GamesCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.v1GamesCreate = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['data'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/games', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v1GamesRead operation.
     * @callback module:api/Api~v1GamesReadCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves a game by id
     * Retrieves a game by id
     * @param {String} gameId 
     * @param {module:api/Api~v1GamesReadCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.v1GamesRead = function(gameId, callback) {
      var postBody = null;

      // verify the required parameter 'gameId' is set
      if (gameId === undefined || gameId === null) {
        throw new Error("Missing the required parameter 'gameId' when calling v1GamesRead");
      }


      var pathParams = {
        'game_id': gameId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/games/{game_id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v1GamesUpdate operation.
     * @callback module:api/Api~v1GamesUpdateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Marks a position in a game
     * Marks a position in a game
     * @param {Object} opts Optional parameters
     * @param {module:model/GameMark} opts.data
     * @param {module:api/Api~v1GamesUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.v1GamesUpdate = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['data'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/games', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
