/**
 * Minesweeper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'src/model/User', 'src/model/GameMark', 'src/model/GameStart', 'src/api/Api', 'api/ApiTokenAuthApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/User'), require('./model/GameMark'), require('./model/GameStart'), require('./api/Api'), require('./api/ApiTokenAuthApi'));
  }
}(function(ApiClient, User, GameMark, GameStart, ApiApi, ApiTokenAuthApi) {
  'use strict';

  /**
   * .<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Minesweeper = require('index'); // See note below*.
   * var xxxSvc = new Minesweeper.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Minesweeper.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Minesweeper.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Minesweeper.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The GameMark model constructor.
     * @property {module:model/GameMark}
     */
    GameMark: GameMark,
    /**
     * The GameStart model constructor.
     * @property {module:model/GameStart}
     */
    GameStart: GameStart,
    /**
     * The Api service constructor.
     * @property {module:api/ApiApi}
     */
    ApiApi: ApiApi,
    /**
     * The ApiTokenAuthApi service constructor.
     * @property {module:api/ApiTokenAuthApi}
     */
    ApiTokenAuthApi: ApiTokenAuthApi
  };

  return exports;
}));
